CREATE TABLE awaitingorders (id int(12) NOT NULL AUTO_INCREMENT, username VARCHAR(50) NOT NULL, symbol VARCHAR(12) NOT NULL, quantity VARCHAR(12), price VARCHAR(12) NOT NULL, limitPrice VARCHAR(12) NOT NULL, stopPrice VARCHAR(12) NOT NULL, PRIMARY KEY(id));

